version: "{build}"

branches:
  only:
    - master

environment:
  nodejs_version: 6.11.4

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i
  - npm i -g gulp

build_script:
  - gulp --require coffeescript/register build

build: on