version: "{build}"

branches:
  only:
    - master
    
environment:
  nodejs_version: 4.7.2

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i -g gulp@^3.9.1
  - npm i

build_script:
  - gulp --require coffee-script/register build

build: on